from rest_framework import serializers

from .models import ShortURL
from .utils import generate_unique_short_code

class ShortURLSerializer(serializers.ModelSerializer):
    """
    Handles serialization and deserialization of ShortURL instances.
    
    READ operations (GET): Returns all fields including a computed 'short_link'.
    WRITE operations (POST): Accepts only 'original_url'. All other fields are
    generated or set automatically by the backend.
    """

    # -------------------------------------------------------------------------
    # COMPUTED FIELDS
    # -------------------------------------------------------------------------

    # SerializerMethodField is read-only by default.
    # It calls get_short_link() below to build the full clickable URL.
    short_link = serializers.SerializerMethodField()

    # -------------------------------------------------------------------------
    # META CONFIGURATION
    # -------------------------------------------------------------------------

    class Meta:
        model = ShortURL
        fields = [
            'id',
            'original_url',
            'short_code',
            'short_link',
            'click_count',
            'created_at',
        ]
        
        # These fields are automatically generated or protected.
        # The client cannot (and should not) send them in a POST request.
        read_only_fields = [
            'id',
            'short_code',
            'short_link',
            'click_count',
            'created_at',
        ]

    # -------------------------------------------------------------------------
    # COMPUTED FIELD LOGIC
    # -------------------------------------------------------------------------

    def get_short_link(self, obj: ShortURL) -> str:
        """
        Build the absolute URL for the short link.
        
        Example output: http://localhost:8000/a3f9k2/
        
        We use the request object from the serializer context so it adapts
        to the current domain (localhost in dev, yourdomain.com in prod).
        """
        request = self.context.get('request')
        if request:
            return request.build_absolute_uri(f'/{obj.short_code}/')
        return f'/{obj.short_code}/'

    # -------------------------------------------------------------------------
    # CREATE LOGIC
    # -------------------------------------------------------------------------

    def create(self, validated_data: dict) -> ShortURL:
        """
        Override create to inject two things that the client does NOT provide:
        1. The authenticated user (from the request context).
        2. A unique short code (generated by our utility).
        """
        # Pull the request from the serializer context.
        # DRF passes the request automatically when you instantiate the
        # serializer with serializer(data=data, context={'request': request}).
        request = self.context.get('request')
        
        # Associate the new URL with the currently logged-in user.
        validated_data['user'] = request.user
        
        # Generate a cryptographically secure, unique short code.
        validated_data['short_code'] = generate_unique_short_code()
        
        # Call the parent ModelSerializer's create() which performs the
        # actual ShortURL.objects.create(**validated_data) and returns the instance.
        return super().create(validated_data)